### ISSUE TITLE
how can i use multi-scales when dec_in is not equal to c_out

### ISSUE THREAD

**Issue by zhuwint** [BorealisAI/scaleformer#1]
Hi~, i want to use multi-scales in my forecast model with `configs.dec_in` not equal to `configs.c_out`. If i set the projection in decoder with `out_channels=c_out`, it would cause boardcast in

https://github.com/BorealisAI/scaleformer/blob/27dcd18f534e49ff50ea1bb742e7352d239ad4ca/models/AutoformerMS.py#L136

is there any solution for it ?

Thanks.

**Comment by aminshabani** [comment]
Hi, It is an interesting question. Following the previous papers, we assume that the model predicts the same series as the input. If you want to extend it, one way can be padding the output with "c_out - c_in" series before concatenation with the input of higher scales. Another way can be replacing the first layer of the models to first embed each of the inputs or the prediction of the previous scale to a fixed dimension (for example d_model) and then concatenate both. 

To replace the exact line that you mentioned, you can simply consider the mean of the common series between both input and output.
