### ISSUE TITLE
Mackey-Glass synthetic data generation?

### ISSUE THREAD

**Issue by jabowery** [BorealisAI/scaleformer#2]
Please provide information on how to run the Mackey-Glass synthetic data generation and how to reproduce the results of the paper.

**Comment by aminshabani** [comment]
Hi, You can use "synthetic" data for Mackey-Glass dataset. For more details on the dataset, please see this part of the code:
https://github.com/BorealisAI/scaleformer/blob/main/data_provider/data_loader.py#L203

**Comment by jabowery** [comment]
You mean like this?

```
from data_provider import data_loader
import numpy as np
import matplotlib.pyplot as plt
data_loader.Dataset_Syn('.',size=(1,1,1))
mg = np.load('Mackey_Glass.npy')
plt.plot(mg)
plt.show()

```
Does `run_all.sh` generate the `Mackey_Glass.npy` file and run the models against it?  If not, how does one do so?

**Comment by aminshabani** [comment]
Yes, `run_all.sh` also creates the dataset to train and also saves `Mackey_Glass.npy` for later checking the provided dataset and visualization.

**Comment by aminshabani** [comment]
The `run_all.sh` script creates the dataset for training and saves `Mackey_Glass.npy` for further verification of the provided dataset and visualization.

**Comment by jabowery** [comment]
In `run.py` I had to change the default for `--data`:

`parser.add_argument('--data', type=str, default='synthetic', help='dataset type')`

**Comment by aminshabani** [comment]
Yes thank you, you can also add it inside of the if condition to run it together with other experiments:
https://github.com/BorealisAI/scaleformer/blob/a83e47ba9a5c54f73c86eed807494d3f52a799b5/run.py#L139-L140
